kubescape/operator

go.mod
go.sum
mainhandler/cronjobhandler.go
mainhandler/handlerequests.go
mainhandler/handlerequestsutils.go
mainhandler/imageregistryhandler.go
mainhandler/imageregistryhandlerhelper.go
mainhandler/kubescapehandler.go
mainhandler/kubescapehandlerhelper.go
mainhandler/vulnscan.go
mainhandler/vulnscanhandler.go

Using consts defined in:
https://github.com/armosec/armoapi-go/blob/master/armotypes/helmconsts.go

Removed consts from component, using consts from armoapi-go

---

go.mod
go.sum
mainhandler/handlerequests.go
mainhandler/imageregistryhandler.go
mainhandler/imageregistryhandlerhelper.go
mainhandler/vulnscan.go

1. Add test registry connectivity command
2.  Change flow to support reading information from command as well (backward compatible)
3. Move part of the functions to registryScan object 
4. Remove ".sig" tags from scans (these are tags created by image signatures, and not valid images for scanning)

Test connectivity

---

README.md

@dwertent as discussed, proposed changes to readme.md.

English, typos and consistency

---

main.go

I opened this PR just so we can trigger the E2E flow

mock change

---

main.go
utils/environmentvariables.go
utils/globalvars.go
watcher/testdata/deployment-two-containers.json
watcher/testdata/deployment.json
watcher/watcher.go
watcher/watcher_test.go

Add cleanUp routine
Missing integration with storage
https://github.com/kubescape/operator/pull/66

cleanUp flow

---

mainhandler/handlerequests.go

Do not trigger host scanner by default

---

mainhandler/imageregistryhandler.go
mainhandler/vulnscan.go

code cleanup

---

watcher/watcher.go

check that pod is running in order to add its imageIDs

check pod status for running

---

mainhandler/vulnscan.go
mainhandler/vulnscan_test.go

add prefix

---

mainhandler/handlerequests.go
mainhandler/handlerequestsutils.go
mainhandler/vulnscan.go
watcher/utils.go
watcher/watcher.go

1 - Use only "scan" API (also for SBOM calculation)
2 - Fix call to vuln-scan readiness probe

change api and fix readiness

---

watcher/watcher.go

fix func name

---

utils/utils.go
utils/utils_test.go
watcher/utils.go
watcher/utils_test.go
watcher/watcher_test.go

extract id only for running containers

---

watcher/watcher.go

use GenerateInstanceIDFromPod

---

watcher/watcher.go

This is needed for generating the instanceID

adding apiversion and kind manually

---

mainhandler/vulnscan.go

add pod kind and apiversion for instanceID

---

go.mod
go.sum
mainhandler/vulnscan.go

support registry api

---

mainhandler/handlerequests.go
mainhandler/vulnscan.go

manually add apiVersion to Pod

---

mainhandler/handlerequests.go
watcher/errors.go
watcher/watcher.go
watcher/watcher_test.go

This PR adds the ability to delete unrecognized vulnerability manifests.
- Includes #120

feat: delete unrecognized Vulnerability Manifests

---

watcher/watcher.go

trigger build

---

mainhandler/vulnscan.go

adding debug log

---

go.mod
mainhandler/vulnscan.go

use calculate parent

---

.github/workflows/relevancy-release.yaml

* Rename image
* Support arm64

Rename image tag

---

watcher/watcher.go

Fix typo in a TODO, trigger image build :roll_eyes:

chore: fix typo in TODO comment

---

mainhandler/imageregistryhandler.go
mainhandler/vulnscan.go

Ticket: https://cyberarmor-io.atlassian.net/browse/SUB-1443
This PR adds support for scanning images from container registries which require authentication.
Up until now, this was only possible for scanning images at the registry, but not for image scanning within a cluster.
Before sending the scan command, we look for all registry scan secrets (those which start with `kubescape-registry-scan`) and look for a match with the ImageTag (a `strings.Contains` comparison). In such case, we add the credentials to the websocket command for kubevuln.
--- 
The documentation describes how to create such secret if it does not exist - https://hub.armosec.io/docs/registry-vulnerability-scan 
A secret for example:
```yaml
kind: Secret
apiVersion: v1
metadata:
name: kubescape-registry-scan-my-acr-secret …
```

Use registry scan secrets for image scanning

---

.github/workflows/pr-merged.yaml

update pr-merged workflow

---

mainhandler/handlerequests.go
mainhandler/vulnscan.go

Remove some logs

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This PR:
1. Updates the Contributing guidelines 
- Update `dev` and `master` to the `main` branch.
- added DCO.
- added link for code of conduct.
3. Updates the PR template (adding a simple check for signed commits)

Minor Fixes in `Contributing.md` and the PR Template

---

.github/workflows/pr-merged.yaml

Fixed workflows

---

build/Dockerfile

Distroless

---

main.go

wait for the context to be done

---

README.md
continuousscanning/doc.go
continuousscanning/loader.go
continuousscanning/loader_test.go

Refactoring
___
This pull request primarily focuses on improving the code formatting in the Go files and fixing a minor issue in the README. The Go files have been formatted using 'gofmt', a tool that automatically formats Go source code. The README file has been updated to correct a syntax error.
___
`continuousscanning/doc.go`: The changes in this file are related to code formatting. The indentation of the comments has been adjusted for better readability.
`continuousscanning/loader.go`: A minor formatting change has been made in the definition of the 'fileFetcher' struct.
`continuousscanning/loader_test.go`: The changes in this file are related to code formatting. The alignment of the struct fields and function parameters has been adjusted for better readability.
`README.md`: A syntax …

gofmt, fix README

---

go.mod
go.sum

Enhancement
___
This PR updates the version of the k8s-interface dependency from v0.0.135 to v0.0.145. This update may include bug fixes, enhancements, or new features in the k8s-interface package that can improve the functionality of the current project.
___
`go.mod`: The k8s-interface version has been updated from v0.0.135 to v0.0.145.
`go.sum`: The checksums for the k8s-interface package have been updated to reflect the new version.
</details>
___

bump k8s-interface version

---

go.mod
go.sum
watcher/watcher_test.go

enhancement
___
- Updated the name of the pod in the test cases in `watcher/watcher_test.go` from "pod-reverse-proxy" to "pod-reverse-proxy-nginx-1ba5-4aaf".
- Bumped the version of the dependency `github.com/kubescape/k8s-interface` from v0.0.153 to v0.0.155 in `go.mod`.
- Updated the checksums for the dependency `github.com/kubescape/k8s-interface` in `go.sum` due to the version bump.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

bump to version 155

---

.github/workflows/hotfix-pr-merged.yaml
main.go

Trigger release

---

continuousscanning/watchbuilder.go
continuousscanning/watchbuilder_test.go

fields arrangement

---

mainhandler/imageregistryhandler.go

SUB-5226 - [Axual] - Can't connect Harbor registry

---

admission/exporter/http_exporter.go

logic that support fields enrichment

---

admission/rules/v1/helpers.go
admission/rules/v1/r2000_exec_to_pod.go

Add comment

---

go.mod
go.sum
mainhandler/vulnscan.go

support harbor registry scan

---

admission/exporter/http_exporter.go
go.mod
go.sum

change exporter registry scan statuses consts names

---

go.mod
go.sum

bump registryx version to support nexus

---

go.mod
go.sum

bump api version with aws display name changes

---

watcher/registryhandler.go

ensure registry cron jobs are in utc timezone

---

watcher/commandswatcher_test.go

change comment

---

.github/workflows/pr-merged.yaml
main.go

Remove old tests

---

admission/rules/v1/r2000_exec_to_pod.go
admission/rules/v1/r2001_portforward.go

Added pod namespace

---

go.mod
go.sum

related PR:
https://github.com/armosec/registryx/pull/18

Update registryx dependency to v0.0.25 and adjust go.sum

---

admission/exporter/http_exporter.go
admission/rules/v1/r2000_exec_to_pod.go

added process tree to exec to pod

---

admission/exporter/http_exporter.go
main.go

Adding support for cloud metadata in admission alerts

---

config/config.go
config/config_test.go
continuousscanning/service_test.go
main.go
mainhandler/kubescapehandlerhelper_test.go
watcher/applicationprofilewatcher_test.go
watcher/commandswatcher_test.go
watcher/podwatcher_test.go
watcher/sbomwatcher_test.go
watcher/watchhandler_test.go

This PR fixes removes service discovery logic (unused var)

remove service discovery logic
