mainhandler/vulnscan.go

quay.io returns "empty token" for bad auth

improve error check

---

mainhandler/imageregistryhandler.go

Fixes SUB-689 when a user tries to add registry scanning for a Harbor registry.
This probably failed for other registries where the URL didn't allow proper type detection.

use RegistryProvider when set to choose registry kind

---

go.mod
go.sum
mainhandler/handlerequests.go
watcher/maps.go
watcher/maps_test.go
watcher/watcher.go
watcher/watcher_test.go

This PR encapsulates a map-and-mutex map of Image hashes to WLIDs in a thread-safe map-like type, so that they can be accessed more conveniently, with less leeway to break synchronization.
To check unit tests, run:
```
go test -v ./watcher -race -failfast -count=1000
```
Other than that, run whatever Operator flows you deem necessary.

refactor: encapsulate ImageIDs to WLIDs map 

---

go.mod
go.sum
mainhandler/handlerequests.go
watcher/errors.go
watcher/maps.go
watcher/maps_test.go
watcher/utils.go
watcher/utils_test.go
watcher/watcher.go
watcher/watcher_test.go

Previously, the ImageID to WLIDs map used values that were sort of like Image IDs, but not really. This is problematic, since the map is supposed to be used as a way to look up entities that have Image Hashes as their keys.
When receiving such an entity, for example, an SBOM, our code cannot meaningfully transform the Image Hash of an SBOM, to an unambiguous, correct Image ID so we can look it up in the Image-WLID map.
Therefore, this map should use Image Hashes instead.
This PR refactors operations on the map to insert by Image Hash instead of Image IDs.
This PR targets the relevancy branch, but requires that #93 is merged first. Check out that PR first.
* Requires #93

fix: Use image hash in WLID map

---

watcher/watcher.go
watcher/watcher_test.go

The podWatcher was using `imageIDs` with tags for searching the `wlidsByImageHash`, which stores imageHashes without tags

fix pod watch and tests

---

watcher/watcher.go
watcher/watcher_test.go

This change makes the WatchHandler use hashed instance IDs of the Filtered SBOMs it watches to check whether it recognizes them or not.

fix: use hashed instance ID to check if a Filtered SBOM is recognized

---

mainhandler/handlerequests.go
watcher/watcher.go
watcher/watcher_test.go

1 - Fix triggering multiple scans for same workload
2 - Remove unused functions
3 - Make `GetWlidsToContainerToImageIDMap` public

fix unecessary scans

---

mainhandler/vulnscan.go
notificationhandler/websocket.go

The Operator failed to trigger scanning for "naked pods".
Here is the error log we see:
```
failed to get container to image ID map for workload wlid://cluster-gke_armo-test-clusters_us-central1-c_dwertent-relevancy/namespace-kube-system/pod-kube-proxy-gke-dwertent-relevancy-default-pool-b43a938e-6996 with err json: Unmarshal(nil *v1.Pod)
```

fix(scan): Fix nil pointer

---

mainhandler/getworkload.go
mainhandler/handlerequestsutils.go
mainhandler/vulnscan.go

Operator was crashing because of a nil pointer access. This was done when logging properties of the instanceID, which was nil. 
After a deeper look, the conclusion is that the instanceID being generated is incorrect, due to the fact that we cannot find Pods which belong to a CronJob in a top-down approach. 
This PR:
1 - Fixes the nil pointer access
2 - Don't send command to scan CronJobs when generating commands for a namespace scan
3 - In case a command was given to scan a CronJob, it will be skipped

dont scan cronjobs && fix nil pointer

---

go.mod
go.sum
main.go
mainhandler/handlecommandresponse.go
mainhandler/handlerequests.go
utils/environmentvariables.go
utils/globalvar_test.go
utils/globalvars.go
utils/types.go
utils/utils.go
watcher/watcher.go
watcher/watcher_test.go

Replaces channel with concurrency.
Set the desired number with the `WORKER_CONCURRENCY` environment variable.

Replace channel with concurrency

---

main.go
mainhandler/handlerequests.go
notificationhandler/websocket.go
notificationhandler/websocket_test.go
notificationhandler/websocketutils.go
restapihandler/restapi.go
restapihandler/triggeraction.go
utils/utils.go

In this PR I replaced the notification and REST API handling so the command will be invoked by the pool and not channel 

core(scan): Replace channel with pool

---

continuousscanning/loader.go
continuousscanning/service.go

This PR removes unused consts and fields. Also triggers a release.

refactor: remove unused entities

---

config/config.go
config/config_test.go
main.go

Refactoring
___
This PR modifies the configuration validation logic to only check for the presence of an AccountID when the Service Discovery feature is enabled. This change is reflected in both the main application logic and the associated tests.
___
`config/config.go`: Removed the check for AccountID from the LoadClusterConfig function. Introduced a new function ValidateConfig that checks for AccountID only if Service Discovery is enabled.
`config/config_test.go`: Added a new test function TestValidateConfig to test the new ValidateConfig function under various scenarios.
`main.go`: Added a call to the new ValidateConfig function to validate the configuration during the application startup.

don't check for accountID without service discovery

---

mainhandler/imageregistryhandler.go
utils/typesutils.go

Enhancement
___
This pull request includes changes to add request headers to the `GetRegistryRepositoriesUrl` function. The changes include:
- Adding a loop to set headers from the `GetRequestHeaders` function in the `SendRepositoriesAndTags` function.
- Changing the `getRequestHeaders` function to `GetRequestHeaders` to make it public.
- Updating the function call in `NewSessionObj` to use the new function name.
___
`mainhandler/imageregistryhandler.go`: Added a loop to set headers from the `GetRequestHeaders` function in the `SendRepositoriesAndTags` function.
`utils/typesutils.go`: Changed the `getRequestHeaders` function to `GetRequestHeaders` to make it public and updated the function call in `NewSessionObj` to use the new function name.
</details> …

Added request headers to GetRegistryRepositoriesUrl

---

mainhandler/imageregistryhandler.go
mainhandler/imageregistryhandlerhelper.go
mainhandler/vulnscan.go

Bug fix
___
This PR addresses issue #173 by ensuring that the namespace configured in the application is used for all Kubernetes operations. Previously, the namespace was hardcoded as `armotypes.KubescapeNamespace`, which could lead to issues if the application was configured to use a different namespace. The changes involve replacing the hardcoded namespace with a call to `config.Namespace()`, which retrieves the currently configured namespace.
___
`mainhandler/imageregistryhandler.go`: Replaced hardcoded namespace with the configured one in various Kubernetes operations such as creating secrets, configmaps, and cronjobs, and getting registry scan secrets and workloads.
`mainhandler/imageregistryhandlerhelper.go`: Updated the namespace used in …

Get namespace name from config

---

continuousscanning/handlers.go
continuousscanning/service_test.go

Enhancement
___
This pull request introduces a new parameter to the continuous scanning feature that allows skipping the host scanner. The changes include:
- Addition of a `HostScanner` parameter in the `makeScanArgs` function in `handlers.go`.
- Refactoring of the test cases in `service_test.go` to accommodate the new parameter.
___
`continuousscanning/handlers.go`: A new parameter `HostScanner` has been added to the `makeScanArgs` function. This parameter is set to false, which means the host scanner will not be triggered for continuous scanning requests.
`continuousscanning/service_test.go`: The test cases have been updated to include the new `HostScanner` parameter. The `IsDeletedScanObject` parameter has also been updated to use the `ptr.To` …

feat(continuousscan): don't trigger host scanner

---

continuousscanning/handlers.go
continuousscanning/service.go
continuousscanning/service_test.go
mainhandler/imageregistryhandlerhelper.go
watcher/watcher.go

bug_fix
___
This PR includes several changes aimed at improving error handling in the codebase. It also restores some previously commented-out code. The main changes are:
- Added error handling for the `deleteCRDs` and `triggerScanFor` functions in `handlers.go`.
- Added error handling for the `Handle` function in `service.go`.
- Restored previously commented-out error handling code in `watcher.go`.
- Changed log level from Info to Error in several places in `imageregistryhandlerhelper.go` to better reflect the severity of the situation.
- Ignored error check in `service_test.go` for `createUnstructuredPod` function.
___
- `continuousscanning/handlers.go`: Added error handling for the `deleteCRDs` and `triggerScanFor` functions.
- …

Error handling, restored commented-out code

---

watcher/watcher.go

bug_fix
___
This PR disables the deletion of Vulnerability Manifests in the WatchHandler. This is a temporary hack and needs to be revisited in the future.
___
- `watcher/watcher.go`: The deletion of Vulnerability Manifests in the HandleVulnerabilityManifestEvents function has been commented out. This prevents the deletion of Vulnerability Manifests when the object is not found.
</details>
___

disable vulnerability manifests deletes

---

go.mod
go.sum
watcher/watcher_test.go

Enhancement
___
- The `k8s-interface` package has been updated from version `v0.0.148` to `v0.0.153`.
- The checksums in `go.sum` have been updated to reflect this change.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><details><summary>2 files</summary><table>
<tr>
<td> …

bump k8s-interface pkg

---

go.mod
mainhandler/imageregistryhandler.go
mainhandler/testdata/vulnscan/registry-secret.json
mainhandler/vulnscan.go
mainhandler/vulnscan_test.go

This PR fixes https://github.com/kubescape/kubevuln/issues/209
When scanning individual images the operator did not send the `skipTLSVerify` and `http` attributes (for insecure registries). These attributes are supported in the registry scan secret 
(see  https://kubescape.io/docs/operator/vulnerabilities/#granting-credentials-directly )
As part of the fix, when parsing the secret, we match the registry name of the scanned image with the registry name in the secret. If such match found, we pass the values to the scan command args.
When scanning image registry, the scan command did include these fields so no change is needed.

send skipTLSVerify and Insecure in image scanning command

---

mainhandler/imageregistryhandler.go
mainhandler/imageregistryhandlerhelper.go

bug_fix, enhancement
___
- Corrected spelling mistakes in error messages and comments.
- Changed slice initialization for clarity and consistency.
- Updated `createTriggerRequestConfigMap` and `setCronJobTemplate` functions to remove unnecessary parameters.
- Fixed incorrect logging message during image scanning.
- Improved error handling and logging for the process of scanning image tags.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>imageregistryhandler.go</strong><dd><code>Refactoring and Bug Fixes in Image Registry Handler</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mainhandler/imageregistryhandler.go
<li>Fixed typos in error …

solved locked routine when image has more than 1 tag

---

admission/rules/v1/helpers.go
admission/rules/v1/r2000_exec_to_pod.go
admission/rules/v1/r2000_exec_to_pod_test.go
admission/rules/v1/r2001_portforward.go
admission/rules/v1/r2001_portforward_test.go

Add ContainerName 

---

mainhandler/vulnscan.go
utils/applicationprofile.go
utils/applicationprofile_test.go

- Change instance ID field in image scan command to use slug (reverts changes in bf8a747)
- Scan application profiles only for complete ones (not partial)

fix: scan complete application profiles

---

go.mod
go.sum

- [x ] Yes, I signed my commits.
This PR updates  k8s-interface to v0.0.187 which contains changes to support google artifact registry.

Update k8s-interface to v0.0.187 to support google artifact registry

---

admission/exporter/http_exporter.go

fix exporter alert data
